### PR TITLE
readme

### PR DESCRIPTION
**Pull request by yousef157**
end my fucking life already please

### CODE REVIEW

**Comment by yousef157** [comment]
image

**Comment by Tanza3D** [comment]
add more spacing

**Comment by yousef157** [comment]
> add more spacing

whatcha mean?

**Comment by yousef157** [comment]
you mean make the text bigger under Issues and Pull Requests?

**Comment by Tanza3D** [comment]
https://i.imgur.com/qLmVQKM.png the spacing between panels.

**Comment by Tanza3D** [comment]
or padding

**Comment by yousef157** [comment]
image
this good enough?

**Comment by Tanza3D** [comment]
mooooore

**Comment by yousef157** [comment]
image
this

**Comment by Tanza3D** [comment]
i can do more.

add inbetween them:
###
###
###

**Comment by Tanza3D** [comment]
welp 
attempt 2 

`###
###
###`

**Comment by Tanza3D** [comment]
im dying

**Comment by yousef157** [comment]
image

image

**Comment by yousef157** [comment]
image

image

**Comment by Tanza3D** [comment]
i'll do it.

**Pull request merged**
